build: off

clone_folder: c:\github.com\nukosuke\go-zendesk

environment:
  GOPATH: c:\go119
  GO111MODULE: on

# temporarily clearing cache to get newer version of Go
#cache:
#  - '%LocalAppData%\go-build'
#  - '%GOPATH%\pkg\mod'

stack: go 1.19

install:
  - go mod download

before_test:
  - go vet ./...

test_script:
  - go test ./...
